Update plugin management
spaceone-dev/console pull request #1032
Opened 2021-02-16 01:57 UTC by danmin20

2021-02-16 04:36 UTC, WANZARGEN requested changes

2021-02-16 04:36 UTC, WANZARGEN commented on src/views/management/supervisor/pages/SupervisorPluginPage.vue
> +                        <p-status v-bind="pluginStateFormatter(value)" class="capitalize" />
여기서 class="capitalize" 를 주는 것보다, 
```src/views/identity/user/lib/helper.ts```
에서 
```
export const pluginStateFormatter = colorBindFactory(pluginStateColor, value => value.toLowerCase());
```
여기에서 ```value.toLowerCase()``` 이부분을 수정하는 것이 이중으로 작업이 들어가지 않아서 더 좋습니다.

2021-02-16 04:36 UTC, WANZARGEN commented on src/views/management/supervisor/pages/SupervisorPluginPage.vue
> +                            <p-status v-bind="pluginStateFormatter(data)" class="capitalize" />
위와 같은 코멘트입니다

2021-02-16 04:36 UTC, WANZARGEN commented on src/views/management/supervisor/pages/SupervisorPluginPage.vue
> +                        <p-status v-bind="pluginStateFormatter(value)" class="capitalize" />
위와 동일한 코멘트입니다.

2021-02-16 04:36 UTC, WANZARGEN commented on src/views/management/supervisor/pages/SupervisorPluginPage.vue
> +            ])),
ref 변수가 참조하고 있는 값(ref.value)의 변경사항을 추적하여, 그 변경된 값에 따라 fields 가 함께 반영되는게 아니라면 굳이 computed 를 쓸 필요가 없습니다.
예를 들어, 각 label 마다 translation key가 부여되고, vm.$t()로 (내부적으로 언어 변경사항을 추적함) 번역된 결과를 각 필드의 label 로 부여하고 싶은 경우에는 computed 가 적절합니다.
예전에 computed 가 어렵다고 하셨던게 기억나서 길게 코멘트 드려요.
computed 는 내부적으로 자바스크립트가 vue composition api를 구현하였는지, 어떤 원리로 변화를 감지하여 반응하는지 매커니즘을 유추하기에 좋은 예입니다.
좀 더 알아보시면 리엑트의 useState 원리와도 맞닿아 있어 두고두고 편리하실 듯 합니다. ㅎㅎ

2021-02-16 04:36 UTC, WANZARGEN commented on src/views/management/supervisor/pages/SupervisorPluginPage.vue
> +            ])),
이 부분은 각 translation code 를 넣은 후, vm.$t()로 번역된 결과를 각 label 에 넣는 방향으로 추가 수정 요청드립니다.

2021-02-17 07:57 UTC, siyeons commented on src/views/management/supervisor/pages/SupervisorPluginPage.vue
> +            ])),
제가 user page에서 테이블 헤더 부분에 computed를 넣었네요 하하;; ㅜㅜ 혼돈을 드려 죄송합니다ㅋㅋㅋ 저도 user page 고쳐놓을게요

2021-02-17 08:02 UTC, WANZARGEN requested changes

2021-02-17 08:02 UTC, WANZARGEN commented on src/views/management/supervisor/pages/SupervisorPluginPage.vue
> +                { name: 'managed', label: vm.$t('MANAGEMENT.SUPERVISOR_PLUGIN.MAIN.DETAILS_BASE_LABEL_MANAGED') },
이렇게 translation 이 들어간 경우에는  computed 로 감싸는게 맞습니다.
이전처럼 정적으로 값이 들어간 경우에 변화를 추적할 이유가 없으므로 computed 로 감쌀 이유가 없어지는 것이고, vm.$t()를 이용한다면 내부적으로 vue i18n 이 locale 변화를 감지하여 변경사항을 반영할 수 있도록 computed로 감싸주어야 합니다.

2021-02-18 06:40 UTC, WANZARGEN approved these changes

2021-02-18 06:49 UTC, merged