feat: alert modals
spaceone-dev/console pull request #1564
Opened 2021-07-09 10:19 UTC by song2kim

### 작업 개요
alert modal 관련 작업

### Jira
https://pyengine.atlassian.net/browse/CLOUD-4727
https://pyengine.atlassian.net/browse/CLOUD-4839
https://pyengine.atlassian.net/browse/CLOUD-4839
https://pyengine.atlassian.net/browse/CLOUD-4774

### 작업 분류
- [X] 버그 수정
- [X] 신규 기능
- [ ] 프로젝트 구조 변경

### 작업 상세 내용
1. acknowledge modal 마크업 (추가 기능구현 작업 필요)
2. resolve modal UI 변경 (추가 기능구현 작업 필요)
3. 다중선택 삭제 모달
4. badge 번역 적용

2021-07-09 10:21 UTC, siyeons commented on src/views/monitoring/alert-manager/lib/helper.ts
>  export const alertStateBadgeStyleTypeFormatter = (alertState) => {
오 ㅎㅎㅎㅎ저도 얘를 사용해야할거같아요...ㅋㅋㅋㅋ

2021-07-09 10:22 UTC, siyeons commented on src/views/monitoring/alert-manager/modules/alert-list/AlertAcknowledgeModal.vue
> +            isAssignToMe: true,
isAssignedToMe가 더 좋을거같아용 ><

2021-07-09 10:24 UTC, siyeons commented on src/views/monitoring/alert-manager/modules/alert-list/AlertActions.vue
> +                <template v-if="field.label === 'Created'">
label이랑 비교하는거보다는~ name==='created_at'처럼 데이터랑 비교하는게 더 좋을거같아요!! 라벨은 언제든 바뀔수도있으니까?! (물론 얜 안바뀌겠지만요 ㅎㅎ)

2021-07-09 10:26 UTC, siyeons commented on src/views/monitoring/alert-manager/modules/alert-list/AlertActions.vue
> +            alertStateI18n: computed(() => ({
i18n을 직접 변수에 쓰는것보단 얘네가 정확히 어떤걸 말하는지로 하는게 좋을거같아요!!(제생각엔..?) 그냥 번역만을 위한건가용??아님 라벨인가요??

2021-07-09 10:26 UTC, siyeons commented on src/views/monitoring/alert-manager/modules/alert-list/AlertActions.vue
> +                state.closeLoading = true;
false로 꺼줘야하지않나요~??

2021-07-09 10:27 UTC, siyeons commented on src/views/monitoring/alert-manager/modules/alert-list/AlertDataTable.vue
> +                        {{ alertStateI18n[value] }}
아 요렇게 쓰이는거군요!!! 보통 이런데에 쓸때는 formatter로 쓰거나 하는거같아요?!

2021-07-09 10:27 UTC, siyeons commented on src/views/monitoring/alert-manager/modules/alert-list/AlertResolveModal.vue
> +                    alerts: props.alerts.map(d => d.alert_id),
여기도 한번 props.alerts?.map으로 해주는게 좋을거같아용!

2021-07-09 10:28 UTC, siyeons commented on src/views/monitoring/alert-manager/modules/alert-list/AlertAcknowledgeModal.vue
> +                });
얘네는 토스트메세지 안띄워도되나요~??

2021-07-09 10:28 UTC, siyeons commented on src/views/monitoring/alert-manager/modules/alert-list/AlertAcknowledgeModal.vue
> +                    alerts: props.alerts.map(d => d.alert_id),
props.alerts?.map 요렇게 해주는게 좋을거같아요!

2021-07-09 10:30 UTC, siyeons approved these changes
수고많으셨어요!!!

2021-07-09 10:46 UTC, WANZARGEN requested changes
고생 많으셨습니다!!! 코멘트 몇 개 달았으니 확인 부탁드려요~!

2021-07-09 10:46 UTC, WANZARGEN commented on src/views/monitoring/alert-manager/lib/helper.ts
> +        break;
```suggestion
    case ALERT_STATE.TRIGGERED: style = 'red100'; break;
```
이렇게 한번 제안드려봅니다.ㅎㅎ

switch 문 쓸 때 짧으면 걍 한줄로 하는게 가독성이 저는 더 좋더라구요!
근데 사람마다 다 다를 것 같아요. 
switch 문 사용에 대해서도 호불호 갈리긴 하는데 논의해보면 좋을 것 같아요!
1. 간단한 매칭 조건문인 경우, 3개 이상 되면 if else 문 말고 switch 문 쓴다. (찬/반)
2. switch 문에서 각 case 문은 처리할 내용이 1줄 정도의 짧은 내용이면 제안한 내용처럼 case, 처리할 내용, break 를 모두 한 줄로 작성한다. (찬/반)

다른 분들은 각각 어떤거 선호하세요??ㅎ

2021-07-09 10:46 UTC, WANZARGEN commented on src/views/monitoring/alert-manager/lib/helper.ts
> +        break;
javascript 에서 if/else vs switch 어떻게 처리하는지 좀 더 알아보고 의견 나눠도 좋겠네요! 이럴 때 공부하는거죠 ㅎ

2021-07-09 10:46 UTC, WANZARGEN commented on src/views/monitoring/alert-manager/modules/alert-list/AlertActions.vue
>                      // eslint-disable-next-line camelcase
이 경우엔  lint disable 처리 안해도 될 것 같네요!

2021-07-09 10:46 UTC, WANZARGEN commented on src/views/monitoring/alert-manager/modules/alert-list/AlertDataTable.vue
> +                        {{ alertStateI18n[value] }}
ㅎㅎ alertStateLabels 라는 변수명이 더 적당해 보입니다

2021-07-09 10:46 UTC, WANZARGEN commented on src/views/monitoring/alert-manager/modules/alert-list/AlertDataTable.vue
> +                    <span>{{ urgencyI18n[value] }}</span>
urgencyLabels 라는 변수명이 더 적당해 보입니다

2021-07-09 10:46 UTC, WANZARGEN commented on src/views/monitoring/alert-manager/modules/alert-list/AlertResolveModal.vue
> -                if (state.noteInput !== undefined) await createNote();
createNote 함수에 try, catch 가 추가되어야 할 것 같습니다.
가장 좋은 것은, 업데이트가 실패한 경우와 노트 생성에 실패한 경우 에러메시지를 따로 주는 것이구요,
그렇게까지는 어렵다면, 어떤 에러가 났을 때 개발자가 무엇으로부터 발생한 에러인지 확인할 수 있도록 콘솔 로그를 남겨주는 정도라도 좋을 것 같습니다.

2021-07-09 10:47 UTC, WANZARGEN commented on src/views/monitoring/alert-manager/modules/alert-list/AlertActions.vue
> +                <template v-if="field.label === 'Created'">
field.name 이 좋아보입니다!

2021-07-09 10:52 UTC, siyeons commented on src/views/monitoring/alert-manager/lib/helper.ts
> +        break;
1은 찬성이고, 2는 좀 애매해요 ㅠㅠ 오히려 좀 길어도 위에꺼가 가독성이 좋게 느껴져서요..!

2021-07-09 10:52 UTC, siyeons commented on src/views/monitoring/alert-manager/lib/helper.ts
> +        break;
조곰만 시간을 주시면..!! 리서치해보겠습니다 ㅎㅎ

2021-07-09 11:04 UTC, yuda110 commented on src/views/monitoring/alert-manager/lib/helper.ts
> +        break;
전 if/else 선호하는 편인데 사실 3개 이상 넘어가는 경우가 잘 없어서, 그때 switch 쓰면 좋겠네요! 물론 말씀하신 대로 간단한 매칭 조건문일 때!
그리고 2번은 뭐든 상관은 없는데 case 들이 통일되면 하면 좋겠어요! 다 1줄로 작성하거나 다 정석(?)으로 쓰거나 이렇게요

2021-07-10 13:15 UTC, song2kim commented on src/views/monitoring/alert-manager/modules/alert-list/AlertAcknowledgeModal.vue
> +                });
`onClickConfirm` 할때 띄워주고 있어서 ~~ 이부분에는 필요없을거같아욯ㅎ

2021-07-10 13:32 UTC, song2kim commented on src/views/monitoring/alert-manager/modules/alert-list/AlertActions.vue
> +                <template v-if="field.label === 'Created'">
아! 요부분은 
```
const TABLE_FIELDS = [
  { name: 'created_at', label: 'Created' },
  { name: 'created_at', label: 'Duration', sortable: false },
]
```
한 개의 데이터가 다르게 created랑 duration 두가지 형태로 보여줘야 해서, 두 개를 구분하는 기준으로 label 기준으로 분기 태웠어요!
혹시 다른 기준이 있을까요?ㅎㅎ

2021-07-10 13:46 UTC, song2kim commented on src/views/monitoring/alert-manager/lib/helper.ts
> +        break;
1번에는 찬성입니다~~! https://aahc.tistory.com/6 요거 보고 switch로 바꿨었욤!
2번은 저는 조금 길게 쓰는게 가독성이 좋게 느껴져요~!

2021-07-12 01:28 UTC, merged

2021-07-12 01:36 UTC, siyeons commented on src/views/monitoring/alert-manager/modules/alert-list/AlertActions.vue
> +                <template v-if="field.label === 'Created'">
아~! 이 필드였군요 ㅎㅎ 그냥 그 테이블의 필드로 구분하신줄 알았어용!!
그럼 union type(enum으로..) 처리해주시는게 좋을거같아요!!