fix: move maintenance window under alert tab
spaceone-dev/console pull request #1636
Opened 2021-07-30 08:34 UTC by WANZARGEN

### 작업 분류
- [ ] 신규 기능
- [ ] 버그 수정
- [x] 기능 개선
- [ ] 리팩토링 및 구조 변경
- [ ] 기타 (문서, CI/CD 워크플로 변경 등)

### 작업 내용
프로젝트 페이지의 maintenance window 탭을 alert 탭 밑으로 내렸습니다.

### 생각해볼 문제

2021-08-02 05:56 UTC, siyeons commented on src/views/monitoring/alert-manager/modules/alert-list/AlertDataTable.vue
> +        }
앗! 이거 설명해주셨는데 까먹었네요 ㅠㅠ ;; 어디에 keep-alive에 대한 룰을 좀 문서화해둘까요??

2021-08-02 05:56 UTC, siyeons requested changes
수고하셨습니다~~~! request change 잘못눌렀어요 ㅠㅠ;;;;

2021-08-02 05:56 UTC, siyeons approved these changes

2021-08-03 01:16 UTC, WANZARGEN commented on src/views/monitoring/alert-manager/modules/alert-list/AlertDataTable.vue
> +        }
네 필요할것 같아용 ㅠㅠ

2021-08-03 01:16 UTC, merged