Feature/user query list
spaceone-dev/console pull request #1787
Opened 2021-11-05 03:23 UTC by JeoungSulMo

### 작업 분류
- [X] 신규 기능
- [ ] 버그 수정
- [ ] 기능 개선
- [ ] 리팩토링 및 구조 변경
- [ ] 기타 (문서, CI/CD 워크플로 변경 등)

### 작업 내용
cost analysis page에서 쿼리관련 API 연결작업을 완료했습니다

- query list
    ![image](https://user-images.githubusercontent.com/50662170/140452075-7eaccbe9-35c6-4df0-8cea-b281fb90a68a.png)
- create, update, delete 모달 별 연결완료

- saveModal 과 Edit Modal이 title만 달랐는데 save모달에서 visibility항목이 제거되어 따로 컴포넌트를 분리하지 않고 visibility항목만 분리 시켰습니다.
    (처음 쿼리를 생성시에 무조건 private으로 생성 된다고 합니다.)
![image](https://user-images.githubusercontent.com/50662170/140452428-50e06163-6282-4540-8b11-6ef108c6e8a2.png)
![image](https://user-images.githubusercontent.com/50662170/140452461-4f6de0d5-5866-434b-852e-27b4c46116c4.png)
    - Edit query 시 query update와 visibility를 수정하는 api가 따로 있어서, 다른 input과 visibility 둘 다 변경하는 경우 요청이 두번 날라가게 된다고 합니다. 

### 질문이요!
- CostAnalysisySaveQueryFormModal을 save와 edit으로 분리 해야하는지 말아야 하는지 잘 모르겠습니다 ㅜㅜ

2021-11-05 05:02 UTC, yuda110 commented on src/services/billing/cost-management/cost-analysis/CostAnalysisPage.vue
>              ],
queryItems에 타입을 넣어주세요. 얘를 씁니다.

```
import { MenuItem } from '@spaceone/design-system/dist/src/inputs/context-menu/type';
```

2021-11-05 05:04 UTC, yuda110 commented on src/services/billing/cost-management/cost-analysis/CostAnalysisPage.vue
>              ],
아, queryItems에 scope도 들어가네요. 그럼 위에서 QueryItem 타입을 명세하고 거기서 MenuItem을 extends하는 게 나을 듯합니다.

2021-11-05 05:14 UTC, yuda110 commented on src/services/billing/cost-management/cost-analysis/CostAnalysisPage.vue
> +                    })),
이것도 괜찮긴 한데 만약 누군가 여길 수정한다 했을 때,
`queryItems`의 기존값을 왜 넣어야 하는지, 어떤 값이 들어있는지 파악해야 하는 수고로움이 있습니다.
넣어야 하는 값이 고정값이니 그냥 넣어줘도 될 것 같습니다.
```
state.queryItems = [
    { name: 'label', label: 'Saved Query', type: 'header' },
    ....
]
```

---
`...item`도 마찬가지입니당.
name, label, scope, type만 필요하니 그냥 `...item` 대신 `name: item.name`을 넣어주는 것도 괜찮을듯합니다.

---

그리고 `scope`는 boolean이니
- 키값을 isPrivate(혹은 isPublic)으로 바꾸거나,
- scope에 그대로 `item.scope`를 넣어 template에서 조작하는 것이 좋을 것 같습니다.

2021-11-05 05:14 UTC, yuda110 commented on src/services/billing/cost-management/cost-analysis/CostAnalysisPage.vue
> +            } catch (e) {
혹시 모르니 여기서 state.queryItems를 초기화해주는 게 좋을듯합니다 :)

2021-11-05 05:16 UTC, yuda110 commented on src/services/billing/cost-management/cost-analysis/CostAnalysisPage.vue
> +                    })),
헛 커밋별로 보느라 수정된 걸 몰랐네요ㅋㅋㅋㅋ 첫 번째는 패스해주세요

2021-11-05 05:18 UTC, yuda110 commented on src/services/billing/cost-management/cost-analysis/CostAnalysisPage.vue
> +        listCostQuerySet();
보통 init 할 때 실행할 함수는 즉시실행 함수로 넣습니다! 대체로 script 가장 하단에 넣어요.

```
(() => {
    listCostQuerySet();
})();
```

2021-11-05 05:20 UTC, yuda110 commented on src/services/billing/cost-management/cost-analysis/CostAnalysisPage.vue
>          const handleClickEditQuery = (myQuery) => {
myQuery 대신 query나 queryItem이라는 이름이 나을 듯합니다!
그리고 타입도 지정해주시면 좋겠습니다~

2021-11-05 05:21 UTC, yuda110 commented on src/services/billing/cost-management/cost-analysis/CostAnalysisPage.vue
> +                }
if / else 안에 있는 코드 각각을 함수로 빼는 게 좋을 것 같습니다~
saveQuery, updateQuery 머 이렇게용

2021-11-05 05:23 UTC, JeoungSulMo commented on src/services/billing/cost-management/cost-analysis/CostAnalysisPage.vue
>          const handleClickEditQuery = (myQuery) => {
앗 저번에도 말씀해주셨는데😭 죄송함다..

2021-11-05 05:28 UTC, yuda110 commented on src/services/billing/cost-management/cost-analysis/lib/config.ts
> +}
먼가 암묵적인 룰이긴 한데, interface엔 보통 Type을 붙이지 않습니다!
```
type visibilityType = 'PUBLIC' | 'PRIVATE'
```

2021-11-05 05:32 UTC, yuda110 commented on src/services/billing/cost-management/cost-analysis/lib/config.ts
> +}
그리고 CostQuerySetType이 사용된 곳을 보니, api 리턴값을 받아올 때 사용되었던데, 이 경우 interface 명을 xxxModel이라고 합니다. 이 경우 CostQuerySetModel이 되겠져

2021-11-05 05:37 UTC, yuda110 commented on src/services/billing/cost-management/cost-analysis/modules/CostAnalysisSaveQueryFormModal.vue
> +    selectedQuery: SavedQueryItemType;
selectedQuery와 SavedQueryItemType라는 타입명이 뭔가 매치가 안 되는 거 같아요!
근데 얘도 걍 query인데 CostQuerySetType 쓰면 안 되는 건가요? 👀

2021-11-05 05:39 UTC, yuda110 commented on src/services/billing/cost-management/cost-analysis/CostAnalysisPage.vue
> +        const handleSaveQueryConfirm = async (emittedData: EmittedSaveQueryDataType) => {
근디 handleSaveQueryConfirm 이거 modal에서 처리해주는 게 어떨까요?

2021-11-05 05:49 UTC, yuda110 commented on src/services/billing/cost-management/cost-analysis/CostAnalysisPage.vue
> +                             height="0.9375rem"
아 width, height는 보통 소숫점 두 자리까지 적습니다!
대체로 1, 1.25, 0.75, 1.5 이렇게 1/4 혹은 1/2로 떨어지게 입력해요.
애매하다면...대강 눈대중으로 적고...QA가 들어오면 그때 고치는 것으로..

그리고 아이콘은 width, heigth 동일한 값 넣습니다!

2021-11-05 05:57 UTC, yuda110 requested changes
후어 리뷰 끝

2021-11-05 06:29 UTC, JeoungSulMo commented on src/services/billing/cost-management/cost-analysis/modules/CostAnalysisSaveQueryFormModal.vue
> +    selectedQuery: SavedQueryItemType;
label이랑 type 이라는 속성 두가지가 더 포함되어있어서 extends하면서 이름이 바뀌었는데 저도 지금보니까 왜 저렇게 썼는지 모르겠네요ㅋㅋㅋㅋ ㅜㅜ 

props로 받은 이후에 사용은 CostQuerySetModel이랑 같아서 빼도 될것 같습니다. 수정할게요!

2021-11-05 06:33 UTC, JeoungSulMo commented on src/services/billing/cost-management/cost-analysis/CostAnalysisPage.vue
> +        const handleSaveQueryConfirm = async (emittedData: EmittedSaveQueryDataType) => {
오.. 그렇네용. 굳이 다시 올려올 필요가 없었네요..! 수정하겠습니당

2021-11-05 07:17 UTC, JeoungSulMo commented
이상한 커밋들 잘 읽어주셔서 감사합니다 ㅜㅜ 담부턴 더 읽기 쉽도록 열심히 작성해 보겠습니다!!
리뷰 매우매우 감사해요!

2021-11-05 07:35 UTC, yuda110 approved these changes
LGTM!

2021-11-05 08:29 UTC, merged

2021-11-07 23:51 UTC, siyeons commented on src/services/billing/cost-management/cost-analysis/CostAnalysisPage.vue
> +        listCostQuerySet();
async인 경우에도 가능해요~!

2021-11-07 23:53 UTC, siyeons commented
수고많으셨어요!!  문서화되어있지 않은 컨벤션이 많군요 ㅠㅠㅠ 일단 노션에 저장해두고 차근차근 문서화해야겠어요 ㅎㅎㅎ