feat: add cost by provider widget
spaceone-dev/console pull request #1874
Opened 2021-11-30 02:29 UTC by JeoungSulMo

### 작업 분류
- [X] 신규 기능
- [ ] 버그 수정
- [ ] 기능 개선
- [ ] 리팩토링 및 구조 변경
- [ ] 기타 (문서, CI/CD 워크플로 변경 등)

### 작업 내용
- CostByProvider 위젯이 추가되었습니다.
![Cost by Provider](https://user-images.githubusercontent.com/50662170/143974832-2c080fa8-f755-4c80-896a-61579bd3d6f5.png)
![Cost by Provider](https://user-images.githubusercontent.com/50662170/143974843-312545e7-79a6-4704-bb87-60c781e971a7.png)

### 생각해볼 문제

2021-11-30 02:38 UTC, song2kim commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +        }
썽모님 요거 `table-style-type="simple"` 스타일 타입이 이번에 생겼어요 ㅠㅠ 수정부탁드려요~!

2021-11-30 02:39 UTC, JeoungSulMo commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +        }
앗 넴넴

2021-11-30 02:41 UTC, song2kim commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +                text-align: right;
테이블 th, td 텍스트 오른쪽 정렬은 dataTable field 에서 `textAlign: 'right'` 설정하여 적용되도록 컴포넌트 스펙에 포함 되어있어요~!ㅎㅎ

2021-11-30 02:45 UTC, song2kim approved these changes
중복 작업 방지를 위해 새로 추가되는 스펙들 공유 열심히 할게용!! 넘 고생많으셨습니다!!ㅎㅎ👍

2021-11-30 03:15 UTC, yuda110 commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +export default {
```suggestion
export default defineComponent<WidgetProps>{
```

2021-11-30 03:20 UTC, yuda110 commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +                const { results } = await SpaceConnector.client.costAnalysis.cost.analyze({
여기서 { result, total_count } 를 받아와 state.totalCount 에 total_count를 넣어주세요!
page limit 때문에 지금처럼 할 경우 chartData에는 최대 15개밖에 들어가지 않아 totalCount를 제대로 받지 못합니다~

2021-11-30 03:20 UTC, yuda110 commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +                        limit: 15,
limit 5개 아닌가용?

2021-11-30 03:21 UTC, yuda110 commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +                        limit: 15,
아 아니구나

2021-11-30 03:24 UTC, yuda110 commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +            await store.dispatch('resource/provider/load');
여긴 페이지가 아닌 위젯이니 리소스 스토어를 load하면 안 됩니다!
가장 상위 페이지인 CostManagementPage에서 provider 리소스를 로드하고 있으니 굳이 안 넣어도 될듯요.

2021-11-30 03:26 UTC, yuda110 commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +                }
데이터 정제하는 부분은 따로 함수로 빼주세요!

2021-11-30 03:27 UTC, yuda110 requested changes
힁님한테 pagination에 따른 차트 데이터 어찌 되는지 여쭤보시고, 차트 데이터가 그대로라면 수정해주세요!

2021-11-30 08:47 UTC, JeoungSulMo commented
파이차트에서는 받아온 데이터 전체를 보여주고 DataTable에서는 5개씩 보여주게 되었습니다!

2021-11-30 10:49 UTC, yuda110 commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +            forEach(response, (d: PieChartRawData) => {
- response보다는 rawData가 좀더 자연스러워보입니다.
- forEach 돌리면 d는 PieChartRawData라는 걸 당연히 알테니 굳이 또 표기하지 않아도 될듯요!

2021-11-30 10:50 UTC, yuda110 commented on src/services/billing/cost-management/widgets/CostByProvider.vue
>              chartData: [] as PieChartRawData[],
여기엔 PieChartRawData가 아니라 PieChartData[] 혹은 PieChartData를 확장한 타입이 필요합니다~

2021-11-30 10:54 UTC, yuda110 commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +                        cost: d.usd_cost,
커스텀 필드(color, label)를 지외한 다른 필드는 웬만하면 billing/cost-management/widgets/type.ts에 정의되어 있는 `PieChartData`를 따라 주세요!
그리고 provider는 안 쓰는 거 같으니 그냥 label을 category로 만드는 게 좋아 보입니다.

```
{
  category: state.providers[d.provider].label || d.provider,
  value: d.usd_cost,
  color: state.providers[d.provider].color || '',
}
```

2021-11-30 11:00 UTC, yuda110 commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +        (async () => { await getData(); })();
얘 하나만 실행하는 거면 async 없어도 될듯여.

2021-11-30 11:03 UTC, yuda110 commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +                    convertToChartData(results);
convertToChartData는 provider가 필요하니 여기에서 말고, 안전하게 바깥에서 providers에 watch를 건 뒤 실행하는 게 좋을 것 같은데...좀 꼼수라서 내일 다른 분들은 어떻게 하는지 물어보고 수정하도록 합시다.

2021-11-30 11:03 UTC, yuda110 reviewed
코멘 몇 개 추가했습니다~

2021-11-30 11:04 UTC, yuda110 commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +                        cost: d.usd_cost,
아, `state.providers[d.provider]`가 없을 수도 있으니 `state.providers[d.provider]?.label` 이렇게 해주세요

2021-11-30 11:25 UTC, siyeons commented on src/services/billing/cost-management/widgets/CostByProvider.vue
>              chartData: [] as PieChartRawData[],
chartData 임시로 any로 해놓은거 있었는데 빨리 고쳐야겠어요 😅 
extends한 타입은 페이지에서 작성해도 될것같아영 저도 그러려구요!

2021-11-30 11:55 UTC, siyeons commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +                    convertToChartData(results);
watch가 필요한 이유는 무엇인가요?? 변경때마다 감지해야할 필요가 있나요? 👀

2021-12-01 04:43 UTC, yuda110 commented on src/services/billing/cost-management/widgets/CostByProvider.vue
> +                    convertToChartData(results);
watch를 걸 필요 없다는 것으로 결론났습니다!!

2021-12-01 04:44 UTC, yuda110 approved these changes
굿굿!!!!!!

2021-12-01 04:48 UTC, merged