Feature/budget stat
spaceone-dev/console pull request #1909
Opened 2021-12-06 10:56 UTC by JeoungSulMo

### 작업 분류
- [X] 신규 기능
- [ ] 버그 수정
- [ ] 기능 개선
- [ ] 리팩토링 및 구조 변경
- [ ] 기타 (문서, CI/CD 워크플로 변경 등)

### 작업 내용
- budgetStat이 costAnalysis budgetPage에 추가되었습니다.
- amountPlanningFilter에 따라 상세 날짜가 바뀌는데 Filter를 임시로 `total`과 `thisMonth` 두가지의 string을 사용했습니다.
- budgetListCard와 budgetList를 같이 사용해 budgetPage부터 props로 내렸습니다.
- budgetListCard에서 parentProjectGroup요청 budgetList요청 두가지 api에대한 loading을 체크하도록 수정되었습니다.
- usei18nDayjs에 description이 추가되었습니다.
    - usei18nDayjs에 파라미터로 dayjs를 넘기면 정상작동하지 않습니다!
![image](https://user-images.githubusercontent.com/50662170/144819846-e73fac41-9212-4129-a7ef-6194513e6963.png)

2021-12-06 12:53 UTC, yuda110 commented on src/common/composables/i18n-dayjs.ts
> + * If you give the dayjs object to the parameter, language changes will not be reflected, so please give parameter with the primitive type.
오호...!

2021-12-06 12:53 UTC, yuda110 commented on src/services/billing/cost-management/budget/BudgetPage.vue
> +            const { results } = await SpaceConnector.client.costAnalysis.budget.list();
try catch를...!

2021-12-06 12:54 UTC, yuda110 commented on src/services/billing/cost-management/budget/BudgetPage.vue
> +            state.loading = false;
loading은 try catch 안에 넣는 게 좋겠어용

2021-12-06 13:00 UTC, yuda110 commented on src/services/billing/cost-management/budget/modules/budget-list/BudgetList.vue
> +            default: () => true,
로딩도 default를 function으로 해야 하나요?! 아마 그냥 true 될 거예요!

2021-12-06 13:02 UTC, yuda110 commented on src/services/billing/cost-management/budget/modules/budget-list/BudgetList.vue
> +        />
근디 이 BudgetList 모듈은 BudgetListCard를 감싸는 것 말고 역할이 또 있나요?
없다면 걍 BudgetPage에서 이 부분 바로 넣어줘도 될 거 같은디

2021-12-06 13:04 UTC, yuda110 commented on src/services/billing/cost-management/budget/modules/budget-list/BudgetListCard.vue
>              const parentProjectGroupName = await getParentProjectGroupName(project_id, project_group_id);
여기 말고 이 위엣 부분이 이번 커밋에 안들어가서 안 눌러지는데.. 이 부분 따로 async 함수로 빼주세요!
SpaceConnector 사용하는 부분은 웬만하면 함수로 빼서 try catch로 감싸는 게 좋습니다 :)

```typescript
await SpaceConnector.client.costAnalysis.budgetUsage.list({
    budget_id,
});
```

2021-12-06 13:09 UTC, yuda110 commented on src/services/billing/cost-management/budget/modules/budget-stat/BudgetStat.vue
> +    budgets: BudgetData[];
여기 loading도 들어가야 할듯요!

2021-12-06 13:13 UTC, yuda110 commented on src/services/billing/cost-management/budget/modules/budget-stat/BudgetStat.vue
> +import { Period } from '@/services/billing/cost-management/cost-analysis/store/type';
앗 제가 좀아까 Period 위치를 (아마) '@/services/billing/cost-management/type' 여기로 옮겨서... 마스터 받고 확인해주세요!

2021-12-06 15:15 UTC, WANZARGEN commented on src/common/composables/i18n-dayjs.ts
> + * If you give the dayjs object to the parameter, language changes will not be reflected, so please give parameter with the primitive type.
오호...! 2

2021-12-06 15:18 UTC, WANZARGEN commented on src/services/billing/cost-management/budget/BudgetPage.vue
> +            loading: true,
```suggestion
            loading: false,
```

2021-12-06 15:19 UTC, WANZARGEN commented on src/services/billing/cost-management/budget/BudgetPage.vue
> +            state.budgets = results;
```suggestion
        const listBudget = async () => {
            if (state.loading) return;
            
            state.loading = true;
            try {
                const { results } = await SpaceConnector.client.costAnalysis.budget.list();
                state.budgets = results;
            } catch(e) { 
                ErrorHandler.handleError(e);
            } finally {
                state.loading = false;
            }

```

2021-12-06 15:24 UTC, WANZARGEN commented on src/services/billing/cost-management/budget/BudgetPage.vue
> +            state.budgets = results;
loading은 관련된 데이터를 가져오는 함수에서 처리하는 컨벤션을 가지고 있어요!
그래야 흐름을 읽기 좋아서요.

데이터를 가져오는 데에 전처리, 후처리로 인해 함수가 복잡해지면,
`fetchData()` 와같이 함수를 분리하고,

```
getData() {
  loading = true;
  fetchData();
  loading = false;
}
````

위처럼 절차적인 관련도가 있는 것들을 모아서, 관리가 편하도록 해주고 있어요!

2021-12-06 15:43 UTC, WANZARGEN commented on src/services/billing/cost-management/budget/modules/budget-list/BudgetList.vue
> +        />
BudgetList 에 statistics(?) 라는 이름의 슬롯을 만들고,
BudgetStat 을 해당 슬롯에 넣도록 하면 어떨까요?

BudgetList 가 props로  budgets 를 받는 것이 아니고,  list api  를 호출하고 필터, 검색 등을 통합적으로 관리하면 좋을 듯 합니다.

- BudgetPage
    - BudgetList
        - statistics slot
        - BudgetListCard
        - Toolbox (pagination, search, etc...)
    - BudgetStat -> BudgetList statistics slot

slot이 복잡하게 느껴진다면, 깔끔하게 아래와 같은 방식도 좋습니다.
- BudgetPage
    - BudgetList
        - BudgetStat
        - BudgetListCard
        - Toolbox (pagination, search, etc...)

@yuda110  의견 부탁드려요~!

2021-12-06 15:47 UTC, WANZARGEN commented on src/services/billing/cost-management/budget/modules/budget-list/BudgetList.vue
> +            default: () => true,
## default 에 function 이 들어가는 타입: non primitive type.

2021-12-06 15:48 UTC, WANZARGEN commented on src/services/billing/cost-management/budget/modules/budget-stat/BudgetStat.vue
> +                <span class="symbol">$</span><span>{{ noBudgets ? '&nbsp;--' : commaFormatter(totalCost.toFixed(2)) }}</span>
symbol 은 display > getters에 현재 currency에 맞는 symbol를 리턴하는 것이 있으니, 그것을 사용하시면 됩니다!

2021-12-06 15:50 UTC, WANZARGEN requested changes
고생 많으셨습니다!!!

2021-12-07 00:22 UTC, JeoungSulMo commented on src/services/billing/cost-management/budget/BudgetPage.vue
> +            const { results } = await SpaceConnector.client.costAnalysis.budget.list();
try catch 미루다 항상.. 안하고 올리네요.. 신경쓰겠습니다ㅜㅜ

2021-12-07 00:49 UTC, JeoungSulMo commented on src/services/billing/cost-management/budget/modules/budget-list/BudgetListCard.vue
>              const parentProjectGroupName = await getParentProjectGroupName(project_id, project_group_id);
앗.. 이부분은 임시로 넣었던 api였던것 같아 제거하겠습니다!

2021-12-07 01:41 UTC, JeoungSulMo commented on src/services/billing/cost-management/budget/modules/budget-stat/BudgetStat.vue
> +import { Period } from '@/services/billing/cost-management/cost-analysis/store/type';
넵! 확인 되었습니다~

2021-12-07 01:47 UTC, siyeons commented on src/common/composables/i18n-dayjs.ts
> + * If you give the dayjs object to the parameter, language changes will not be reflected, so please give parameter with the primitive type.
오호 🤩

2021-12-07 01:47 UTC, siyeons commented on src/services/billing/cost-management/budget/BudgetPage.vue
> +            loading: true,
왜 초기 로딩이 false여야 하나요??👀👀

2021-12-07 01:51 UTC, siyeons reviewed
다른 분들이 너무 리뷰 잘 주신 것 같아요!! 담번에 pr 올릴 땐
BudgetList/BudgetPage 수정사항과
BudgetStat 수정 사항을 따로 올려주시면 조금 더 자세한 리뷰가 가능할 것 같아요~!

2021-12-07 01:53 UTC, siyeons commented on src/services/billing/cost-management/budget/BudgetPage.vue
> +            state.loading = false;
근데 이거 마스터에 제가 수정해놓지않았었나요..?! 🥲 컨플릭트 날것같은데..!

2021-12-07 03:11 UTC, song2kim commented on src/services/billing/cost-management/budget/modules/budget-stat/BudgetStat.vue
> +    }
스크린 사이즈 관련 코드는 해당 코드 끼리 모아서 작성하기로 했거든요~!
위에 작성된 mobile 관련 코드 여기에 한번에 작성해주시면 좋을것 같습니다!

2021-12-07 03:23 UTC, JeoungSulMo commented on src/services/billing/cost-management/budget/BudgetPage.vue
> +            state.loading = false;
#1908 여기까지 리베이스 받았을 때는 따로 컨플릭트 없었습니다!

2021-12-07 03:24 UTC, JeoungSulMo commented on src/services/billing/cost-management/budget/modules/budget-list/BudgetList.vue
> +        />
slot으로 한번 수정해 봤습니당

2021-12-07 05:45 UTC, JeoungSulMo commented
BudgetStat
- currencyMoneyFormatter를 적용하였습니다.
- currency 선택 부분이 없어서 일단 항상 달러로 표시되어 있도록 되어있습니다.

BudgetList/BudgetPage
- 완진님이 해주신 리뷰처럼 Stat을 slot을 BudgetList에 추가 하였습니다.

이 외에 리뷰 주신 부분들도 수정이 완료되었습니다. 리뷰 감사합니다!!!

2021-12-08 01:18 UTC, yuda110 commented on src/services/billing/cost-management/budget/modules/budget-stat/BudgetStat.vue
> +                <span class="symbol">$</span><span>{{ noBudgets ? '&nbsp;--' : commaFormatter(totalCost.toFixed(2)) }}</span>
currency가 전역이라서 다른 페이지(ex. Cost Dashboard)에서 currency가 바뀌면 여기도 바뀝니다!

2021-12-08 01:53 UTC, WANZARGEN commented on src/services/billing/cost-management/budget/modules/budget-list/BudgetList.vue
> +        />
budget page 가 아닌  budget list 가 api 호출도 담당하여야 budget list가 따로 빠져있는 의미가 있어보여요. budget page는 단순히 모듈을 조합하고, url query string 로직이 있어야 해서 list api 호출과 같은 작업이 없었으면 합니다.

> BudgetList 가 props로 budgets 를 받는 것이 아니고, list api 를 호출하고 필터, 검색 등을 통합적으로 관리하면 좋을 듯 합니다.

2021-12-08 01:54 UTC, WANZARGEN commented on src/services/billing/cost-management/budget/BudgetPage.vue
> +        </budget-list>
budget page 가 아닌 budget list 가 api 호출도 담당하여야 budget list가 따로 빠져있는 의미가 있어보여요. budget page는 단순히 모듈을 조합하고, url query string 로직이 있어야 해서 list api 호출과 같은 작업이 없었으면 합니다.

BudgetList 가 props로 budgets 를 받는 것이 아니고, list api 를 호출하고 필터, 검색 등을 통합적으로 관리하면 좋을 듯 합니다.

2021-12-08 01:54 UTC, WANZARGEN commented on src/services/billing/cost-management/budget/BudgetPage.vue
> +        })();
budget page 가 아닌 budget list 가 api 호출도 담당하여야 budget list가 따로 빠져있는 의미가 있어보여요. budget page는 단순히 모듈을 조합하고, url query string 로직이 있어야 해서 list api 호출과 같은 작업이 없었으면 합니다.

BudgetList 가 props로 budgets 를 받는 것이 아니고, list api 를 호출하고 필터, 검색 등을 통합적으로 관리하면 좋을 듯 합니다.

2021-12-08 01:55 UTC, WANZARGEN commented on src/services/billing/cost-management/budget/BudgetPage.vue
> +            loading: true,
https://alive-abacus-288.notion.site/API-UX-e6ea2dec9c9343aebd8f2dd58b836fa4

2021-12-08 01:58 UTC, WANZARGEN requested changes
Budget Page 가 아닌 Budget List가 list api 호출을 담당하도록 변경 부탁드립니다!

2021-12-08 01:59 UTC, WANZARGEN commented on src/services/billing/cost-management/budget/modules/budget-stat/BudgetStat.vue
> +                <span class="symbol">$</span><span>{{ noBudgets ? '&nbsp;--' : commaFormatter(totalCost.toFixed(2)) }}</span>
요거 한번만 더 기획사항 확인해볼게요.. ㅠ

2021-12-08 02:22 UTC, JeoungSulMo commented
@WANZARGEN 변경 완료 되었습니다!  budgetList에서 toolbox 할때 가능하면 조회까지 해보겠슴다!

2021-12-08 06:09 UTC, WANZARGEN commented on src/services/billing/cost-management/budget/modules/budget-list/BudgetList.vue
> +        </slot>
```suggestion
        <slot name="statistics" />
```

2021-12-08 06:09 UTC, WANZARGEN commented on src/services/billing/cost-management/budget/BudgetPage.vue
> +        </budget-list>
```suggestion
        <budget-list>
            <template #statistics>
                        <budget-stat :loading="loading" :budgets="budgets" />
            </template>
        </budget-list>
```

2021-12-08 06:12 UTC, WANZARGEN commented on src/services/billing/cost-management/budget/modules/budget-list/BudgetList.vue
> +        </slot>
budget list data가 그대로 쓰인다면, slot이 굳이 필요없을 것 같아요!

2021-12-08 06:12 UTC, WANZARGEN commented on src/services/billing/cost-management/budget/BudgetPage.vue
> +        </budget-list>
budget stat이 budget list data가 그대로 사용되고, 그 바탕으로 그려지는거라면... budget list 안에 그냥 있으면 될거같아요!

2021-12-08 06:13 UTC, WANZARGEN approved these changes
확인하였습니다! 코멘트 2개 달았습니다! (마이너합니다)

2021-12-08 07:04 UTC, merged