feat: add fixDate button to costDashboardPage
spaceone-dev/console pull request #2156
Opened 2022-01-27 09:12 UTC by JeoungSulMo

### To Reviewers
- [ ] Skip

### 작업 분류
- [X] 신규 기능
- [ ] 버그 수정
- [ ] 기능 개선
- [ ] 리팩토링 및 구조 변경
- [ ] 기타 (문서, CI/CD 워크플로 변경 등)

### 작업 내용
- fix date 토글이 추가되었습니다.
    ![image](https://user-images.githubusercontent.com/50662170/151327324-7053cdea-5809-4f57-b5a0-dd15efc0a279.png)
    ![image](https://user-images.githubusercontent.com/50662170/151327969-48ffd318-a55c-4364-82d7-b7ea0aea2570.png)

- 툴팁에대한 정보가 아직 디자인에 올라와있지 않아 일단 아이콘만 먼저 배치해 두었습니다.

### 생각해볼 문제

2022-01-27 09:14 UTC, WANZARGEN commented on src/services/billing/cost-management/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
> +            <p-i name="ic_tooltip" width="1rem" height="1rem" />
기획 문서에도 없나용?

2022-01-27 09:17 UTC, JeoungSulMo commented on src/services/billing/cost-management/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
> +            <p-i name="ic_tooltip" width="1rem" height="1rem" />
넵넵 물음표 툴팁을 넣어야 한다는 표시는 있는데 추가적인 설명이 없었습니다!

2022-01-27 09:18 UTC, JeoungSulMo commented on src/services/billing/cost-management/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
> +            <p-i name="ic_tooltip" width="1rem" height="1rem" />
![image](https://user-images.githubusercontent.com/50662170/151329079-89c3e72e-0862-49ce-907d-e33252d5efc4.png)

2022-01-27 09:19 UTC, JeoungSulMo commented on src/services/billing/cost-management/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
> +            <p-i name="ic_tooltip" width="1rem" height="1rem" />
앗 discussion에 물어보면 될까요??

2022-01-27 09:56 UTC, siyeons approved these changes
성모님 감사합니다! 툴팁이나 이후 진행상황 반영 등등은 제가 할게요!!! 도와주셔서 감사드려요~~! 👍👍

2022-01-27 09:56 UTC, siyeons commented on src/services/billing/cost-management/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
> +                           :disabled="selectedFixDate"
별건아니지만ㅋㅋ boolean값이기때문에
isFixDateSelected 
이런식으로 되면 더 좋아요!!!

2022-01-27 10:07 UTC, yuda110 commented on src/services/billing/cost-management/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
> +            selectedFixDate: !!Object.keys(props.fixedPeriod).length,
여긴 computed로 해야 하지 않나요우?

2022-01-27 10:08 UTC, yuda110 approved these changes
귯귯

2022-01-27 10:30 UTC, WANZARGEN commented on src/services/billing/cost-management/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
> +            <p-i name="ic_tooltip" width="1rem" height="1rem" />
네!!! ㅎㅎ

2022-01-27 10:36 UTC, WANZARGEN commented on src/services/billing/cost-management/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
> +
api 상에 period 데이터는 변경되었지만, 상위 컴포넌트에는 변경사항이 반영되지 않는 문제가 있습니다.

api 호출이 성공한 경우 추가적으로 `update` 이벤트를 emit하여, 상위 컴포넌트가 가지고 있는 dashboard 데이터에도 변경된 `state.period`가 반영되어야 합니다.

아마 그렇게 하면 아래의  `props.fixedPeriod` watch 가 동작할겁니다.
해당 컴포넌트에서 변경한 사항이 위로 갔다가, 다시 같은 객체가 props 로 주입되는 것이라 동작하지 않기를 원하지만,
`props.fixedPeriod` watcher 입장에서는 어쨌든 `props.fixedPeriod`가 바뀐 것이므로, 동작합니다.
이를 위해 `props.fixedPeriod`와 `state.period`가 같은 객체인지 확인이 필요하겠지요.

2022-01-27 10:37 UTC, WANZARGEN requested changes
데이터의 일관성을 잃을 가능성이 있는 부분이 있어, 수정 요청드립니다.

2022-01-27 10:47 UTC, WANZARGEN commented on src/services/billing/cost-management/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
> +
흠 그런데 위에 대시보드에서.. 매번 `getDashboardLayout` 를 하는군요. 
그럼 항상 갱신된 상태를 보장하므로 문제없어보입니다.
그러나 만약 상위 컴포넌트가 `period_type` 정보를 다른 곳에서도 사용한다면, `getDashboardLayout` 를 호출하기 전까지(다른 대시보드를 갔다가 돌아오기 전까지)는 변경사항이 반영이 안되므로 문제가 생길 수 있습니다.

2022-01-27 10:50 UTC, WANZARGEN approved these changes

2022-01-27 12:54 UTC, JeoungSulMo commented on src/services/billing/cost-management/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
> +                           :disabled="selectedFixDate"
앗.. 저번에 블로그 봤었는디... 수정할게욤

2022-01-27 13:47 UTC, mustit-devkbs commented on src/services/billing/cost-management/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
> +
**킹완진 쫌치네?????????**

2022-01-28 02:50 UTC, JeoungSulMo commented
대시보드쪽의 FixedPeriod와 selectDropdown의 FixedPeriod 값을 일치시켜 일관성이 유지되도록 수정해 보았습니다.

- `fix date` 토글을 on/off할 때, 완진님 말씀대로 같은 period를 가져도 watch가 작동하여 새로 렌더링 되었고, 이 부분을 해결하기위해 period와 fixed date를 비교하였습니다.
- 추가로 처음 렌더링이 될 때와 대시보드 이동시에 비교에 있어서 fixedPeriod에대한 비교가 필요해 추가되었습니다

2022-01-28 02:52 UTC, JeoungSulMo commented on src/services/billing/cost-management/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
> +            selectedFixDate: !!Object.keys(props.fixedPeriod).length,
는 페이지쪽 dashboard와 연결되며 다시 생겼습니다 😄

2022-01-28 03:09 UTC, WANZARGEN commented on src/services/billing/cost-management/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
> +                emit('update:fixed-period', periodType, fixedPeriod);
```suggestion
                emit('update:fixed-period', periodType);
                 emit('update:period', fixedPeriod);
```

뷰에서 'update:xxx' 이벤트는 prop을 양방향 바인딩할 수 있도록하는 sync 기능을 위해 사용되는 이벤트명이므로, 관련된 prop만 이벤트 파라미터로 넘기는게 좋을 것 같습니다.

2022-01-28 03:15 UTC, WANZARGEN commented on src/services/billing/cost-management/cost-dashboard/modules/CostDashboardPeriodSelectDropdown.vue
> +            if (isEqual(props.fixedPeriod, state.period) || (isObjectEmpty(before) && !isObjectEmpty(after))) return;
```suggestion
            if (after === state.period || (isObjectEmpty(before) && !isObjectEmpty(after))) return;
```

참조값 비교만 하여도 아래에서 위로 올려준 객체인지 아닌지를 구별 가능하므로, isEqual 로 감싸지 않아도 좋을 것 같습니다.

2022-01-28 03:25 UTC, WANZARGEN commented on src/services/billing/cost-management/cost-dashboard/CostDashboardPage.vue
> +            state.fixedPeriod = fixedPeriod;
dashboard-layouts 컴포넌트에 period state가 바인딩되고 있는데, period은 어디에서도 변경해주고 있지 않네요.
그러면 period를 아무리 바꾸주어도 각 위젯들에 반영이 안되고 있을 것 같은데...

이 페이지에서는 `fixedPeriod`, `period` state가 각각 있을 필요가 없어보입니다.
어차피 `period` 값은 2개 이상이 될 수 없고, 그것이 고정인지 아닌지만 달라지는 것이 아닌지요.
(제가 잘못이해하고 있다면 알려주세요 😅)

오히려 `period`, `periodType` 이렇게 두 개 state가 있는게 맞아보입니다.

2022-01-28 03:25 UTC, WANZARGEN reviewed
수정사항 확인했고, 코멘트 달았습니다!

2022-01-28 05:56 UTC, merged