feat: apply costAnalysis table style to the pdf
spaceone-dev/console pull request #2284
Opened 2022-02-24 03:09 UTC by JeoungSulMo

### To Reviewers
- [ ] Skip

### 작업 분류
- [X] 신규 기능
- [ ] 버그 수정
- [ ] 기능 개선
- [ ] 리팩토링 및 구조 변경
- [ ] 기타 (문서, CI/CD 워크플로 변경 등)

### 작업 내용
- costAnalysis table의 스타일을 pdf에 적용했습니다.
- 환률 적용시 한글과 한문이 깨져 pdf용 폰트를 따로 적용했습니다.

- 한글
    ![Pasted Graphic 1](https://user-images.githubusercontent.com/50662170/155450317-f542351e-5e98-48df-b7d3-276a842ce0c1.png)

### 생각해볼 문제

2022-02-24 04:15 UTC, WANZARGEN requested changes
와 디자인 거의 비슷하게 나왔네요 ㅎㅎ 훌륭합니다.
컴포넌트 인터페이스 관련해서 변경이 필요한 부분이 있어, 그 부분 수정 해주시면 재검토 하겠습니다!

2022-02-24 04:15 UTC, WANZARGEN commented on src/common/components/layouts/PdfDownloadOverlay.vue
> +            costAnalysis: {
```suggestion
            DataTable: {
```
pdf download overlay 컴포넌트는 콘솔의 특정 서비스에서 사용되는 것이 아니므로, 범용적인 네이밍이 좋을 것 같습니다!

2022-02-24 04:15 UTC, WANZARGEN commented on src/common/components/layouts/PdfDownloadOverlay.vue
> +                    return 9;
:+1:

2022-02-24 04:15 UTC, WANZARGEN commented on src/styles/fonts.ts
> +export const PdfFontType = Object.freeze({
```suggestion
export const pdfFonts = Object.freeze({
```

type 정의가 아니면 카멜케이스로 정의합니다.
type이 아니므로 Type postfix가 없으면 더 좋을 것 같습니다!

2022-02-24 04:15 UTC, WANZARGEN commented on src/common/components/layouts/PdfDownloadOverlay.vue
> +            }),
`src/common/components/` 아래의 컴포넌트들은 design system component로 옮겨질 가능성이 있는 컴포넌트들로, 
store의 값을 직접 가지지 않고 props로 넘겨받는 방식으로 작성되어야 합니다!
font를 prop으로 빼내어, 사용하는 쪽에서 주입하도록 변경 부탁드립니다!

2022-02-24 04:15 UTC, WANZARGEN commented on src/common/components/layouts/PdfDownloadOverlay.vue
>  (pdfMake as any).vfs = pdfFonts.pdfMake.vfs;
그럼 이 부분이 필요없어지나요?

2022-02-24 04:17 UTC, JeoungSulMo commented on src/common/components/layouts/PdfDownloadOverlay.vue
>  (pdfMake as any).vfs = pdfFonts.pdfMake.vfs;
일단 폰트관련해서는 vfs과 관계가 없어집니다!

2022-02-24 04:19 UTC, WANZARGEN commented
> vfs : nodeModules/pdfmake 아래에서 커스텀할 폰트를 추가하고 라이브러리 자체적으로 빌드를 한번 돌려 적용해야 했고
http : http요청으로 폰트를 받아와 적용하는 방식
이렇게 두가지 방법으로 로딩이 가능한데, 현재 전역 객체 window.location.origin에서 origin도메인을 불러와 폰트를 적용시켰습니다.
이 방법으로 진행해도 될까요??

네 좋습니다 ㅎㅎ

2022-02-24 04:19 UTC, WANZARGEN commented on src/common/components/layouts/PdfDownloadOverlay.vue
>  (pdfMake as any).vfs = pdfFonts.pdfMake.vfs;
아 필요없어지면 삭제 부탁드려요~!

2022-02-24 04:20 UTC, WANZARGEN commented on src/common/components/layouts/PdfDownloadOverlay.vue
> +            }),
prop 이름은 font url? 이런 식으로 'http://...' string이라는 것이 명확하게 전달되는 이름이었으면 합니다.

2022-02-24 04:21 UTC, WANZARGEN commented on src/common/components/layouts/PdfDownloadOverlay.vue
> +            }),
관련 문서 링크도 주석으로 달려있으면 좋겠습니다!

2022-02-25 05:00 UTC, WANZARGEN approved these changes
너무나 고생 많으셨습니다 👏
정말 마이너한 코멘트와 방어코드가 필요한 부분에 코멘트 드렸습니다!
그 외에는 모두 LGTM 입니다!

2022-02-25 05:04 UTC, siyeons commented on src/common/components/layouts/PdfDownloadOverlay/fonts.ts
> +export type LanguageType = typeof fontLanguages[keyof typeof fontLanguages];
저도 자주 뒤에 Type을 붙였었는데 앞으로는 좀 고쳐야겠군요..😅

2022-02-25 05:22 UTC, merged