feat: add tooltip to the  AWSDataTransferCostTrend table header
spaceone-dev/console pull request #2516
Opened 2022-04-05 09:28 UTC by JeoungSulMo

### To Reviewers
- [ ] Skip

### 작업 분류
- [X] 신규 기능
- [ ] 버그 수정
- [ ] 기능 개선
- [ ] 리팩토링 및 구조 변경
- [ ] 기타 (문서, CI/CD 워크플로 변경 등)

### 작업 내용
- costDashboardDataTable에 tooltip을 추가가 가능하도록 구현했습니다.

![image](https://user-images.githubusercontent.com/50662170/161721353-b6189a72-0de3-4ea5-90b9-dd895802dbd6.png)

CostDashboardDataTable에 header tooltip에 대한 정보를 props로 넘겨 렌더링 하도록 구현되었습니다.
### 생각해볼 문제

2022-04-05 09:33 UTC, yuda110 commented on src/services/cost-explorer/widgets/AWSDataTransferCostTrend.vue
> +            ]),
이렇게 tooltips를 관리하면 데이터(name)를 수동으로 일치시켜야 해서 신경쓸 것이 많아질 듯합니다.
DataTableField를 extends한 새로운 Field 타입을 만들어 fields 하나로 관리하는 게 어떨까요?

```
interface Field extends DataTableField {
  tooltipText?: string;
}
```

2022-04-05 09:34 UTC, yuda110 commented on src/services/cost-explorer/widgets/modules/CostDashboardDataTable.vue
> +            <template v-for="tooltip in headerTooltips" v-slot:[`th-${tooltip.name}-format`]="{ field }">
fields 하나로 관리한다면 여기서 fields를 사용해도 되겠죠!

2022-04-05 09:35 UTC, yuda110 commented on src/services/cost-explorer/widgets/modules/CostDashboardDataTable.vue
> +                    <p-tooltip :contents="tooltip.content" position="bottom" class="tooltip-btn">
사소한 거긴 한데ㅋㅋㅋㅋ
btn 같은 줄임말 웬만하면 안 쓰기로 해서 button으로 바꾸는 게 좋겠습니다!!!

2022-04-05 09:36 UTC, yuda110 requested changes
코멘 달았습니다!!!

2022-04-05 09:40 UTC, yuda110 approved these changes
나머진 LGTM..!
제가 곧 퇴근할거라..

2022-04-05 14:13 UTC, WANZARGEN approved these changes
깔끔합니다! LGTM!
component -> directive 방식으로 사용 방식 개선을 제안드립니다!

2022-04-05 14:13 UTC, WANZARGEN commented on src/services/cost-explorer/widgets/modules/CostDashboardDataTable.vue
> +                    <p-tooltip v-if="field.tooltipText" :contents="field.tooltipText" position="bottom"
v-tooltip 사용하는건 어떠세요?? 
p-tooltip 가능하면 사용 안하려구요! 불필요하게 컴포넌트 관리할 필요가 없어서요.
storybook에 directive 도 작성해둬야 겠네요.

v-tooltip 사용된 곳이 많으니, 전체검색 하셔서 엿보신 후 반영하시는 방향을 추천드려요!

2022-04-06 00:52 UTC, JeoungSulMo commented
directive 방식으로 툴팁 적용 및 currency별 심볼이 추가되지 않아 추가하였습니다.
@song2kim 님 툴팁 부분에 번역적용이 필요합니다! 🙏 🙏

2022-04-06 00:56 UTC, merged